// This service provide data for statApp
// gRPC only

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: api/fakeDataSourceApp.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time           string  `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	GasPrice       float64 `protobuf:"fixed64,2,opt,name=gasPrice,proto3" json:"gasPrice,omitempty"`
	GasValue       float64 `protobuf:"fixed64,3,opt,name=gasValue,proto3" json:"gasValue,omitempty"`
	Average        float64 `protobuf:"fixed64,4,opt,name=average,proto3" json:"average,omitempty"`
	MaxGasPrice    float64 `protobuf:"fixed64,5,opt,name=maxGasPrice,proto3" json:"maxGasPrice,omitempty"`
	MedianGasPrice float64 `protobuf:"fixed64,6,opt,name=medianGasPrice,proto3" json:"medianGasPrice,omitempty"`
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_fakeDataSourceApp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_api_fakeDataSourceApp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_api_fakeDataSourceApp_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *Transaction) GetGasPrice() float64 {
	if x != nil {
		return x.GasPrice
	}
	return 0
}

func (x *Transaction) GetGasValue() float64 {
	if x != nil {
		return x.GasValue
	}
	return 0
}

func (x *Transaction) GetAverage() float64 {
	if x != nil {
		return x.Average
	}
	return 0
}

func (x *Transaction) GetMaxGasPrice() float64 {
	if x != nil {
		return x.MaxGasPrice
	}
	return 0
}

func (x *Transaction) GetMedianGasPrice() float64 {
	if x != nil {
		return x.MedianGasPrice
	}
	return 0
}

type ResponseCurrencyInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ethereum *ResponseCurrencyInfo_Transactions `protobuf:"bytes,1,opt,name=ethereum,proto3" json:"ethereum,omitempty"`
}

func (x *ResponseCurrencyInfo) Reset() {
	*x = ResponseCurrencyInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_fakeDataSourceApp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseCurrencyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseCurrencyInfo) ProtoMessage() {}

func (x *ResponseCurrencyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_fakeDataSourceApp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseCurrencyInfo.ProtoReflect.Descriptor instead.
func (*ResponseCurrencyInfo) Descriptor() ([]byte, []int) {
	return file_api_fakeDataSourceApp_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseCurrencyInfo) GetEthereum() *ResponseCurrencyInfo_Transactions {
	if x != nil {
		return x.Ethereum
	}
	return nil
}

type RequestCurrencyInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *RequestCurrencyInfo) Reset() {
	*x = RequestCurrencyInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_fakeDataSourceApp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestCurrencyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCurrencyInfo) ProtoMessage() {}

func (x *RequestCurrencyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_fakeDataSourceApp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCurrencyInfo.ProtoReflect.Descriptor instead.
func (*RequestCurrencyInfo) Descriptor() ([]byte, []int) {
	return file_api_fakeDataSourceApp_proto_rawDescGZIP(), []int{2}
}

func (x *RequestCurrencyInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ResponseCurrencyInfo_Transactions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transactions []*Transaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
}

func (x *ResponseCurrencyInfo_Transactions) Reset() {
	*x = ResponseCurrencyInfo_Transactions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_fakeDataSourceApp_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseCurrencyInfo_Transactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseCurrencyInfo_Transactions) ProtoMessage() {}

func (x *ResponseCurrencyInfo_Transactions) ProtoReflect() protoreflect.Message {
	mi := &file_api_fakeDataSourceApp_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseCurrencyInfo_Transactions.ProtoReflect.Descriptor instead.
func (*ResponseCurrencyInfo_Transactions) Descriptor() ([]byte, []int) {
	return file_api_fakeDataSourceApp_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ResponseCurrencyInfo_Transactions) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

var File_api_fakeDataSourceApp_proto protoreflect.FileDescriptor

var file_api_fakeDataSourceApp_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x61, 0x6b, 0x65, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x41, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x66,
	0x61, 0x6b, 0x65, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x41, 0x70, 0x70,
	0x22, 0xbd, 0x01, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x67, 0x61, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x08, 0x67, 0x61, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x61,
	0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x61, 0x78, 0x47, 0x61, 0x73,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x6d, 0x61, 0x78,
	0x47, 0x61, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x6d, 0x65, 0x64, 0x69,
	0x61, 0x6e, 0x47, 0x61, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x0e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x6e, 0x47, 0x61, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x22, 0xbc, 0x01, 0x0a, 0x14, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x50, 0x0a, 0x08, 0x65, 0x74, 0x68,
	0x65, 0x72, 0x65, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x66, 0x61,
	0x6b, 0x65, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x41, 0x70, 0x70, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79,
	0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x08, 0x65, 0x74, 0x68, 0x65, 0x72, 0x65, 0x75, 0x6d, 0x1a, 0x52, 0x0a, 0x0c, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x42, 0x0a, 0x0c, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x66, 0x61, 0x6b, 0x65, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x41, 0x70, 0x70, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22,
	0x29, 0x0a, 0x13, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x63, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0x78, 0x0a, 0x18, 0x66, 0x61,
	0x6b, 0x65, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x41, 0x70, 0x70, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5c, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x26, 0x2e, 0x66, 0x61, 0x6b, 0x65, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x41, 0x70, 0x70, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x27, 0x2e, 0x66, 0x61, 0x6b, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x41, 0x70, 0x70, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x49, 0x6e,
	0x66, 0x6f, 0x22, 0x00, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x4d, 0x61, 0x74, 0x68, 0x50, 0x6f, 0x65, 0x6d, 0x2f, 0x73, 0x74, 0x61, 0x74,
	0x41, 0x70, 0x70, 0x2f, 0x70, 0x6b, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_fakeDataSourceApp_proto_rawDescOnce sync.Once
	file_api_fakeDataSourceApp_proto_rawDescData = file_api_fakeDataSourceApp_proto_rawDesc
)

func file_api_fakeDataSourceApp_proto_rawDescGZIP() []byte {
	file_api_fakeDataSourceApp_proto_rawDescOnce.Do(func() {
		file_api_fakeDataSourceApp_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_fakeDataSourceApp_proto_rawDescData)
	})
	return file_api_fakeDataSourceApp_proto_rawDescData
}

var file_api_fakeDataSourceApp_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_fakeDataSourceApp_proto_goTypes = []interface{}{
	(*Transaction)(nil),                       // 0: fakeDataSourceApp.Transaction
	(*ResponseCurrencyInfo)(nil),              // 1: fakeDataSourceApp.ResponseCurrencyInfo
	(*RequestCurrencyInfo)(nil),               // 2: fakeDataSourceApp.RequestCurrencyInfo
	(*ResponseCurrencyInfo_Transactions)(nil), // 3: fakeDataSourceApp.ResponseCurrencyInfo.Transactions
}
var file_api_fakeDataSourceApp_proto_depIdxs = []int32{
	3, // 0: fakeDataSourceApp.ResponseCurrencyInfo.ethereum:type_name -> fakeDataSourceApp.ResponseCurrencyInfo.Transactions
	0, // 1: fakeDataSourceApp.ResponseCurrencyInfo.Transactions.transactions:type_name -> fakeDataSourceApp.Transaction
	2, // 2: fakeDataSourceApp.fakeDataSourceAppService.GetData:input_type -> fakeDataSourceApp.RequestCurrencyInfo
	1, // 3: fakeDataSourceApp.fakeDataSourceAppService.GetData:output_type -> fakeDataSourceApp.ResponseCurrencyInfo
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_fakeDataSourceApp_proto_init() }
func file_api_fakeDataSourceApp_proto_init() {
	if File_api_fakeDataSourceApp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_fakeDataSourceApp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_fakeDataSourceApp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseCurrencyInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_fakeDataSourceApp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestCurrencyInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_fakeDataSourceApp_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseCurrencyInfo_Transactions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_fakeDataSourceApp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_fakeDataSourceApp_proto_goTypes,
		DependencyIndexes: file_api_fakeDataSourceApp_proto_depIdxs,
		MessageInfos:      file_api_fakeDataSourceApp_proto_msgTypes,
	}.Build()
	File_api_fakeDataSourceApp_proto = out.File
	file_api_fakeDataSourceApp_proto_rawDesc = nil
	file_api_fakeDataSourceApp_proto_goTypes = nil
	file_api_fakeDataSourceApp_proto_depIdxs = nil
}
