// This service provide statistic info about changing currency
// gRPC & REST

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: api/statApp.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestDayPriceAvg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *RequestDayPriceAvg) Reset() {
	*x = RequestDayPriceAvg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_statApp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestDayPriceAvg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDayPriceAvg) ProtoMessage() {}

func (x *RequestDayPriceAvg) ProtoReflect() protoreflect.Message {
	mi := &file_api_statApp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDayPriceAvg.ProtoReflect.Descriptor instead.
func (*RequestDayPriceAvg) Descriptor() ([]byte, []int) {
	return file_api_statApp_proto_rawDescGZIP(), []int{0}
}

func (x *RequestDayPriceAvg) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type ResponseDayPriceAvg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DayPriceAvg float64 `protobuf:"fixed64,1,opt,name=dayPriceAvg,proto3" json:"dayPriceAvg,omitempty"`
}

func (x *ResponseDayPriceAvg) Reset() {
	*x = ResponseDayPriceAvg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_statApp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseDayPriceAvg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseDayPriceAvg) ProtoMessage() {}

func (x *ResponseDayPriceAvg) ProtoReflect() protoreflect.Message {
	mi := &file_api_statApp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseDayPriceAvg.ProtoReflect.Descriptor instead.
func (*ResponseDayPriceAvg) Descriptor() ([]byte, []int) {
	return file_api_statApp_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseDayPriceAvg) GetDayPriceAvg() float64 {
	if x != nil {
		return x.DayPriceAvg
	}
	return 0
}

var File_api_statApp_proto protoreflect.FileDescriptor

var file_api_statApp_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x41, 0x70, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x74, 0x61, 0x74, 0x41, 0x70, 0x70, 0x1a, 0x1c, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x28, 0x0a, 0x12, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x79, 0x50, 0x72, 0x69, 0x63, 0x65, 0x41, 0x76, 0x67,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x65, 0x22, 0x37, 0x0a, 0x13, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x44, 0x61, 0x79, 0x50, 0x72, 0x69, 0x63, 0x65, 0x41, 0x76, 0x67, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x61, 0x79, 0x50, 0x72, 0x69, 0x63, 0x65, 0x41, 0x76, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x0b, 0x64, 0x61, 0x79, 0x50, 0x72, 0x69, 0x63, 0x65, 0x41, 0x76, 0x67, 0x32, 0x7c, 0x0a,
	0x0e, 0x53, 0x74, 0x61, 0x74, 0x41, 0x70, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x6a, 0x0a, 0x0b, 0x44, 0x61, 0x79, 0x50, 0x72, 0x69, 0x63, 0x65, 0x41, 0x76, 0x67, 0x12, 0x1b,
	0x2e, 0x73, 0x74, 0x61, 0x74, 0x41, 0x70, 0x70, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x44, 0x61, 0x79, 0x50, 0x72, 0x69, 0x63, 0x65, 0x41, 0x76, 0x67, 0x1a, 0x1c, 0x2e, 0x73, 0x74,
	0x61, 0x74, 0x41, 0x70, 0x70, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61,
	0x79, 0x50, 0x72, 0x69, 0x63, 0x65, 0x41, 0x76, 0x67, 0x22, 0x20, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x1a, 0x12, 0x18, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x2f, 0x64, 0x61, 0x79, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x41, 0x76, 0x67, 0x2f, 0x7b, 0x64, 0x61, 0x74, 0x65, 0x7d, 0x42, 0x21, 0x5a, 0x1f, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4d, 0x61, 0x74, 0x68, 0x50, 0x6f,
	0x65, 0x6d, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x41, 0x70, 0x70, 0x2f, 0x70, 0x6b, 0x67, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_statApp_proto_rawDescOnce sync.Once
	file_api_statApp_proto_rawDescData = file_api_statApp_proto_rawDesc
)

func file_api_statApp_proto_rawDescGZIP() []byte {
	file_api_statApp_proto_rawDescOnce.Do(func() {
		file_api_statApp_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_statApp_proto_rawDescData)
	})
	return file_api_statApp_proto_rawDescData
}

var file_api_statApp_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_statApp_proto_goTypes = []interface{}{
	(*RequestDayPriceAvg)(nil),  // 0: statApp.RequestDayPriceAvg
	(*ResponseDayPriceAvg)(nil), // 1: statApp.ResponseDayPriceAvg
}
var file_api_statApp_proto_depIdxs = []int32{
	0, // 0: statApp.StatAppService.DayPriceAvg:input_type -> statApp.RequestDayPriceAvg
	1, // 1: statApp.StatAppService.DayPriceAvg:output_type -> statApp.ResponseDayPriceAvg
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_statApp_proto_init() }
func file_api_statApp_proto_init() {
	if File_api_statApp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_statApp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestDayPriceAvg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_statApp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseDayPriceAvg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_statApp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_statApp_proto_goTypes,
		DependencyIndexes: file_api_statApp_proto_depIdxs,
		MessageInfos:      file_api_statApp_proto_msgTypes,
	}.Build()
	File_api_statApp_proto = out.File
	file_api_statApp_proto_rawDesc = nil
	file_api_statApp_proto_goTypes = nil
	file_api_statApp_proto_depIdxs = nil
}
